<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <AssemblyVersion>10.0.1.0</AssemblyVersion>
	  <FileVersion>10.0.1.0</FileVersion>
	  <Version>10.0.1.0</Version>    
	  <ApplicationIcon>theRightDirection.ico</ApplicationIcon>
    <Company>the Right Direction BV</Company>
    <Copyright>the Right Direction BV</Copyright>
    <PackageProjectUrl>https://www.therightdirection.nl</PackageProjectUrl>
    <PackageIcon>tRD-icon-v-400.jpg</PackageIcon>
    <RepositoryUrl>https://www.therightdirection.nl</RepositoryUrl>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>C:\GitHub\SharedLibraries\</OutputPath>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="tRD-icon-v-400.jpg" />
	</ItemGroup>

  <ItemGroup>
    <Content Include="theRightDirection.ico" />
    <Content Include="tRD-icon-v-400.jpg">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Ben.Demystifier" Version="0.4.1" />
    <PackageReference Include="Refit" Version="10.1.6" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="theRightDirection.Library" Version="10.0.0" />
  </ItemGroup>
</Project>
