<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
	  <TargetFramework>net9.0-windows</TargetFramework>
	  <Nullable>enable</Nullable>
	  <UseWPF>true</UseWPF>
	  <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>theRightDirection.WPF.Xaml</AssemblyName>
    <RootNamespace>theRightDirection.WPF.Xaml</RootNamespace>
	  <AssemblyVersion>9.0.0.0</AssemblyVersion>
	  <FileVersion>9.0.0.0</FileVersion>
	  <Version>9.0.0.0</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Company>the Right Direction BV</Company>
    <Copyright>the Right Direction BV</Copyright>
    <PackageProjectUrl>https://www.therightdirection.nl</PackageProjectUrl>
    <PackageIcon>tRD-icon-v-400.jpg</PackageIcon>
    <RepositoryUrl>https://www.therightdirection.nl</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>C:\GitHub\SharedLibraries\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
	  <Content Include="tRD-icon-v-400.jpg">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
	  </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="theRightDirection.Library" Version="8.0.8" />
  </ItemGroup>
</Project>