<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
	  <TargetFramework>net10.0-windows</TargetFramework>
	  <Nullable>enable</Nullable>
	  <UseWPF>true</UseWPF>
	  <ImplicitUsings>enable</ImplicitUsings>    
	  <RootNamespace>theRightDirection.WPF.Controls</RootNamespace>
    <AssemblyName>theRightDirection.WPF.Controls</AssemblyName>
	  <AssemblyVersion>10.0.0.0</AssemblyVersion>
	  <FileVersion>10.0.0.0</FileVersion>
	  <Version>10.0.0.0</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Company>the Right Direction BV</Company>
    <Copyright>the Right Direction BV</Copyright>
    <PackageProjectUrl>https://www.therightdirection.nl</PackageProjectUrl>
    <RepositoryUrl>https://www.therightdirection.nl</RepositoryUrl>
    <PackageIcon>tRD-icon-v-400.jpg</PackageIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>C:\GitHub\SharedLibraries\</OutputPath>
  </PropertyGroup>

	<ItemGroup>
		<Content Include="tRD-icon-v-400.jpg">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</Content>
	</ItemGroup>


	<ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MahApps.Metro.IconPacks.BootstrapIcons" Version="6.2.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3856.49" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="theRightDirection.Library" Version="8.0.8" />
  </ItemGroup>
</Project>